# Generated by Django 4.1.3 on 2023-03-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedbacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.TextField(max_length=50)),
                ("f_email", models.TextField(max_length=50)),
                ("f_contact", models.TextField(max_length=50)),
                ("f_message", models.TextField(max_length=100)),
            ],
        ),
    ]
