# Generated by Django 4.1.3 on 2023-03-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS_user", "0005_delete_turfreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turfreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_name", models.TextField(max_length=50)),
                ("r_contact", models.TextField(max_length=50)),
                ("r_message", models.TextField(max_length=100)),
            ],
        ),
    ]
