# Generated by Django 4.1.3 on 2023-03-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TMS_user", "0006_turfreview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Turfreview",
        ),
    ]
