# Generated by Django 4.1.3 on 2023-03-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TMS_user", "0008_turfreview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Turfreview",
        ),
    ]
