# Generated by Django 4.1.3 on 2023-03-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TMS_admin", "0006_managerlist_turf_cost"),
        ("TMS_user", "0010_turfreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("b_name", models.TextField(max_length=50)),
                ("b_contact", models.TextField(max_length=20)),
                ("b_turf", models.TextField(max_length=50)),
                ("b_cost", models.TextField(max_length=10)),
                ("b_date", models.DateField()),
                ("b_tst", models.TimeField()),
                ("b_tend", models.TimeField()),
                ("b_tcost", models.TextField(max_length=10)),
                ("b_status", models.TextField(max_length=50)),
                ("b_pstatus", models.TextField(max_length=50)),
                (
                    "mn_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TMS_admin.managerlist",
                    ),
                ),
                (
                    "us_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TMS_admin.userlist",
                    ),
                ),
            ],
        ),
    ]
