# Generated by Django 4.1.3 on 2023-03-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TMS_user", "0012_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="mn_id",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="us_id",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Feedbacks",
        ),
        migrations.RemoveField(
            model_name="turfreview",
            name="m_id",
        ),
        migrations.RemoveField(
            model_name="turfreview",
            name="u_id",
        ),
        migrations.DeleteModel(
            name="Bookings",
        ),
        migrations.DeleteModel(
            name="Turfreview",
        ),
    ]
