# Generated by Django 4.1.3 on 2023-03-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adminlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_name", models.TextField(max_length=100)),
                ("admin_pass", models.TextField(max_length=100)),
            ],
        ),
    ]
