# Generated by Django 4.1.3 on 2023-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS_admin", "0002_managerlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.TextField(max_length=50)),
                ("user_email", models.TextField(max_length=50)),
                ("user_mobile", models.TextField(max_length=50)),
                ("user_username", models.TextField(max_length=50)),
                ("user_password", models.TextField(max_length=50)),
                ("user_confpassword", models.TextField(max_length=50)),
            ],
        ),
    ]
