# Generated by Django 4.1.3 on 2023-03-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS_admin", "0003_userlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerlist",
            name="turf_desc",
            field=models.TextField(max_length=500, null=True),
        ),
    ]
