# Generated by Django 4.1.3 on 2023-03-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TMS_admin", "0004_managerlist_turf_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turfimages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="images/")),
                (
                    "manager_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TMS_admin.managerlist",
                    ),
                ),
            ],
        ),
    ]
